Repository PoCInnovation/Workshops, pull requests merged in 2022-08, with the labels that each got.

#38 software: Fixes for 03.Prisma
  software/03.Prisma/README.md
  software/03.Prisma/SETUP.md
Labels: bug, dependencies

#37 software: Fixes for 12.GraphQL-Apollo
  software/12.GraphQL-Apollo/README.md
  software/12.GraphQL-Apollo/sources/backend.zip
  software/12.GraphQL-Apollo/sources/frontend.zip
Labels: bug, dependencies

#36 01.React: Renew of the React workshop
  software/01.React/README.md
  software/01.React/SETUP.md
Labels: documentation, enhancement

#34 28.gin
  software/28.Gin/.assets/request-item-display.png
  software/28.Gin/README.md
  software/28.Gin/SETUP.md
  software/28.Gin/controllers/.gitkeep
  software/28.Gin/database/database.go
  software/28.Gin/database/database.json
  software/28.Gin/middlewares/.gitkeep
  software/28.Gin/routes/.gitkeep
Labels: enhancement

#40 Fixes for 17.gRPC
  software/17.gRPC/README.md
  software/17.gRPC/SETUP.md
Labels: bug, enhancement

#48 Fixes for 06.Nest
  software/06.Nest/README.md
  software/06.Nest/SETUP.md
  software/06.Nest/src/step-2/article.dto.ts
  software/06.Nest/src/step0/learn.md
  software/06.Nest/src/step2/article.dto.ts
  software/06.Nest/src/step3/database.service.ts
Labels: enhancement
